apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitch
  name: speedometer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: speedometer
  strategy: {}
  template:
    metadata:
      labels:
        component: speedometer
    spec:
      # initContainers:
      # - name: wait-for-zookeeper
      #   image: jwilder/dockerize
      #   args: ["-wait", "tcp://kafka:9092", "-timeout", "10s"]
      containers:
      - image: ermineaweb/speedometer:latest
        name: speedometer
        resources: {}
status: {}
