apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitch
    service: speedometer
  name: speedometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitch
  strategy: {}
  template:
    metadata:
      labels:
        app: twitch
    spec:
      containers:
      - image: ermineaweb/chat-speedometer:latest
        name: speedometer
        resources: {}
status: {}
