apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitch
  name: streamnotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      component: streamnotifier
  strategy: {}
  template:
    metadata:
      labels:
        component: streamnotifier
    spec:
      initContainers:
      - name: wait-for-kafka
        image: ermineaweb/stream-notifier:latest
        command: ["sh", "-c", "until kcat -q -b kafka:9092 -t topic_healthcheck -L; do echo 'try again'; sleep 3; done"]
      containers:
      - name: streamnotifier
        image: ermineaweb/stream-notifier:latest
        resources: {}
status: {}
