apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: twitch
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper:latest
        name: zookeeper
        ports:
          - name: main
            containerPort: 2181
        envFrom:
          - configMapRef:
              name: env-zookeeper
        resources: {}