apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: twitch
    component: kafka
  name: kafka
spec:
  replicas: 1
  serviceName: "kafka"
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      # initContainers:
      # - name: wait-for-zookeeper
      #   image: jwilder/dockerize
      #   args: ["-wait", "tcp://zookeeper:2181", "-timeout", "10s"]
      containers:
      - image: bitnami/kafka:latest
        name: kafka
        ports:
          - name: main
            containerPort: 9092
        envFrom:
          - configMapRef:
              name: env-kafka
        resources: {}