apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitch
  name: serverrest
spec:
  replicas: 1
  selector:
    matchLabels:
      component: serverrest
  strategy: {}
  template:
    metadata:
      labels:
        component: serverrest
    spec:
      initContainers:
      - name: wait-for-kafka
        image: ermineaweb/server-rest:latest
        command: ["sh", "-c", "until kcat -q -b kafka:9092 -t topic_healthcheck -L; do echo 'try again'; sleep 3; done"]
      containers:
      - name: serverrest
        image: ermineaweb/server-rest:latest
        ports:
          - name: main
            containerPort: 3000
        resources: {}
status: {}
